### ISSUE TITLE
进入recovery后出现问题

### ISSUE THREAD

**Issue by jzlyff** [ymdzq/OFRP-device_xiaomi_elish#1]
在进入recovery后使用"twrp decrypt"命令解密data后 adb莫名断开且平板进入MTP模式(挂载储存)
取消密码后 进入recovery后将直接进入MTP模式 无法连接adb进行操作
驱动运行正常，电脑USB接口无异常

**Comment by ymdzq** [comment]
额，我这里无法复现，recovery的默认usb设置就是开启mtp+adb模式，mtp跟adb不冲突，酷安上是看见有过酷友反馈说无法使用adb，我刚刚试了加锁屏密码使用twrp decrypt命令依然无法复现，
![QQ截图20230324230033](https://user-images.githubusercontent.com/1422091/227562091-0ae3e391-b827-4655-b230-1de98f6c88b7.jpg)
正常的流程是在系统中如果能正常授权、使用adb，第一屏结束进入recovery开始马上就能连上adb，无加密、解密之后会自动重新加载data并重启adbd，即可重新输入adb命令正常刷机
可以试试更新一下adb工具
https://developer.android.google.cn/studio/releases/platform-tools?hl=zh-cn
