### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by 1904097914** [ymdzq/OFRP-device_xiaomi_elish#12]
大佬 我目前是小米平板5Pro(elish) 刷了vk的870内核 目前内核版本是4.19.273 看介绍好像是可以固化的 想问一下是不是直接用电脑刷入后进rec再刷入那个zip卡刷包就可以了啊 如果我有root的话 能不能用第三方软件在开机软件刷入啊

**Comment by ymdzq** [comment]
zip刷入rec的原理是修补boot里的ramdisk，好像在scene或者爱玩机工具箱的付费版看到过类似的功能，我自己没有用过，
因为我没有付费vk内核，只在暮间雾的那个内置了vk内核的移植包上测试过，所以不确定是不是vk内核每个付费版本都能用，他说他给vk付费版里提过加上兼容rec的代码，所以免费内核和旧版本如果没有加上那段代码固化之后就无法点亮屏幕，
我自己都是先在电脑上临时启动rec，进入rec后重刷当前rom刷机包里提取的vendor_boot.img，然后在rec里刷入rec的zip卡刷包和vk内核zip卡刷包，无所谓顺序，先刷rec和先刷内核都一样，刷完就固化好了，下次直接重启进入rec就是橙狐了，
因为临时启动和刷内核都会动vendor_boot，互相覆盖，所以最好先还原rom自带的vendor_boot，然后再按我的方法一起刷过，保证效果
因为刷入rec会修补boot，如果你的root是用的ksu就没影响，如果是用的面具就会掉root，就要重刷面具卡刷包，或者用备份功能把现在的boot分区备份出来，然后开机修补你备份出来的boot.emmc.win文件，重新刷入boot分区

**Comment by 1904097914** [comment]
感谢大佬，问了vk的作者，他说在付费版本中加了兼容的代码。
手机刷入镜像我看有几个软件 比如镜像助手 scene之类的 不太了解原理 就先用电脑刷了 后续也方便救砖
我自己用的是最新版的德尔塔面具 大概看了一下内容 是不是先备份vendor_boot 带内核的boot分区然后再准备好vk内核卡刷包和rec卡刷包 用电脑临时启动rec 在刷入rec和内核最后刷入boot啊 有点没太听懂

**Comment by ymdzq** [comment]
这个东西有电脑挺简单的，刷不坏，自己试几次就明白了

**Comment by 1904097914** [comment]
vendor_boot是非要在刷机包里提取吗 我在开机状态直接提取可以吗

**Comment by 1904097914** [comment]
总结了一下
是这样吗
1.刷vendor_boot
2.刷rec卡刷包
3.刷vk卡刷包
4.刷boot/magisk卡刷包
看到酷安上有人刷蓝屏的 想问一下会不会砖啊 有多大风险 用的是主力机有点害怕

**Comment by 1904097914** [comment]
如果是安装完面具后备份的boot 是不是在最后直接刷boot就行不用刷面具卡刷包了啊

**Comment by 1904097914** [comment]
"而刷入橙狐后如果后续没有刷rom替换掉vendor_boot就重启进入系统，可能会影响当前系统稳定性"这里没太看明白 就是官核用完rec直接重启会不稳定吗

**Comment by 1904097914** [comment]
另外对密码有要求吗 能不能设密码 或者说设什么类型的密码

**Comment by 1904097914** [comment]
感谢大佬 已经刷上了 第一次没固化成功 第二次临时启动又是关闭avb2.0校验然后重启前又装一遍 最后才成功 就是启动速度太慢了 比我开机都慢 每次打开还要解密data 然后又要很长时间 还留了一大堆日志 解密data还会报错 但是不影响使用 想问一下如果我之后刷机把boot刷进去了 这个rec是不是就没了 我要是想它不被覆盖的话怎么办 需要调整吗

**Comment by 1904097914** [comment]
另外我要是想更内核的话怎么办 rec会掉吗
