### ISSUE TITLE
[問題]是否會將一些問題解答或是其他項目紀錄在wiki 頁面內

### ISSUE THREAD

**Issue by skysumbra** [ymdzq/OFRP-device_xiaomi_elish#5]
你好，
目前持有一台手機realme x7pro  android 12 ，該手機系統更新已經EOL，
系統是單分區，super 為動態，並且已經解鎖。
另外也可以去借pixel 手機來用，因此，我在嘗試學習建立recovery，工具是使用 github 上的[twrpdtgen-master](https://www.google.com/search?client=firefox-b-e&q=twrpdtgen-master) 來練習建立devie tree。

但有些疑問，不曉得是否可以請教或是有機會參考你這邊的過去的紀錄？
謝謝。

**Comment by ymdzq** [comment]
wiki页面大概是不会写了，我不是很会用github，而且作为业余项目，不会花太多时间在这上面，
我不是很推荐用天玑处理器的手机练习，会变得不幸，首先不支持fastboot boot file.img命令，只能直接刷入recovery或者boot分区，而recovery分区刷入错误的文件或者使用reboot recovery命令很可能导致手机无限重启无法使用，可能需要用Bypass bootrom、sp flash之类的方法救活，非常麻烦
记录可以随意参考，毕竟就是为了学习交流开源的，我自己也参考了很多其他人的记录

**Comment by skysumbra** [comment]
請問我是否詢問你以前閱讀項目是什麼才知道這樣產生device tree，目前我是用程式產生的，推測還要修改增加內容後才可以使用，但是不知道是要加入什麼
另外我有找到其他人寫的device tree ，但是系統為android 11
也請問是否有使用社交工具，例如TG,QQ等，可以加好友嗎？偶爾詢問下，主要還是想靠自己成功編譯

**Comment by ymdzq** [comment]
主要是直接在github上搜索同品牌或者同处理器的其他dt，或者反编译现成twrp镜像对比差别，
有现成dt就更好抄了，升级版本大部分改动就只是改个版本号、换内核以及其他提取自rom的文件就好了，
能开机了就看adb logcat慢慢修，缺什么补什么，
mtk手机的data解密比较麻烦，方案很多而且依赖的文件有版本要求，比较随缘，没有缘分一辈子也修不好。
加好友就算了吧，很多你不懂的我也不懂，业余搞搞机，有时间不如买新手机，刷机没有前途的
