### ISSUE TITLE
[question]如何獲取第三方REC

### ISSUE THREAD

**Issue by skysumbra** [ymdzq/OFRP-device_xiaomi_elish#7]
你好
假設嘗試建立一份簡陋device tree，接下來如何獲取最新的REC codebase ?
目前常見的有TWRP，PBRP，OFRP，他們都是可以使用相同的device tree 嗎? 如何獲取最新且小容量的codebase，
方法好像是用repo，有嘗試安裝好Ubuntu18 於VM內(由於disk capacity so smaller，想說放在host  disk上，但是repo 在外部位置上提示得repo init，我一直失敗)

請問以下路徑是否是目前最新且是正確的網址?
TWRP:
https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp

PBRP:
https://github.com/PitchBlackRecoveryProject/manifest_pb

OFRP:
https://wiki.orangefox.tech/en/home

**Comment by ymdzq** [comment]
他们都是基于platform_manifest_twrp_aosp，只有几个文件夹不同而已，
硬盘至少空余100g以上，内存16g以上，加钱买硬盘或者学习云编译，
dt的话，都是以twrp为基础，PBRP是要往BoardConfig.mk里面加点东西，
OFRP是要往vendorsetup.sh里面加点东西，我另一个手机的仓库有写

**Comment by skysumbra** [comment]
一開始是用在host disk 上，就是Ubuntu18  vm(VirtualBox) 掛載外部 win 第二個ssd  上
路徑是/media/sf_other/twrp

```
user@user-VirtualBox:/media/sf_other/twrp$ repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
Downloading Repo source from https://gerrit.googlesource.com/git-repo
repo: error: "git" failed with exit status 128
  cwd: /media/sf_other/twrp/.repo/repo.tmp
  cmd: ['git', 'config', 'remote.origin.url', 'https://gerrit.googlesource.com/git-repo']
  stderr:
  >> fatal: not in a git directory
fatal: double check your --repo-rev setting.
fatal: cloning the git-repo repository failed, will remove '.repo/repo' 

user@user-VirtualBox:/media/sf_other/twrp$ 
```
但是一直不行，請問你知道這個如何解決嗎?
如果是在vm 內則是正常，就可以繼續下一步，但是會導致VM 不夠(剩下2GB)
```
user@user-VirtualBox:~$ repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
Downloading Repo source from https://gerrit.googlesource.com/git-repo
repo: warning: Invalid UTF-8 output:
cmd: ['git', 'tag', '-v', 'v2.32']
b'gpg: Signature made \xe5\xbb\xbf\xe5\xbb\xbf\xe4\xb8\x89\xe5\xb9\xb4\xe4\xb8\x89\xe6\x9c\x88\xe4\xb8\x80\xe6\x97\xa5 (\xe9\x80\xb1\xe4\xb8\x89) \xe4\xba\x8c\xe6\x99\x82\xe5\xbb\xbf\xe4\xb8\x89\xe5\x88\ngpg:                using DSA key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65\ngpg: Good signature from "Repo Maintainer <repo@android.kernel.org>" [unknown]\ngpg: WARNING: This key is not certified with a trusted signature!\ngpg:          There is no indication that the signature belongs to the owner.\nPrimary key fingerprint: 8BB9 AD79 3E8E 6153 AF0F  9A44 1653 0D5E 920F 5C65\n'

Your identity is: besov007 <besov007@gmail.com>
If you want to change this, please re-run 'repo init' with --config-name

repo has been initialized in /home/user

```

**Comment by skysumbra** [comment]
> 一開始是用在host disk 上，就是Ubuntu18 vm(VirtualBox) 掛載外部 win 第二個ssd 上 路徑是/media/sf_other/twrp
> 
> ```
> user@user-VirtualBox:/media/sf_other/twrp$ repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
> Downloading Repo source from https://gerrit.googlesource.com/git-repo
> repo: error: "git" failed with exit status 128
>   cwd: /media/sf_other/twrp/.repo/repo.tmp
>   cmd: ['git', 'config', 'remote.origin.url', 'https://gerrit.googlesource.com/git-repo']
>   stderr:
>   >> fatal: not in a git directory
> fatal: double check your --repo-rev setting.
> fatal: cloning the git-repo repository failed, will remove '.repo/repo' 
> 
> user@user-VirtualBox:/media/sf_other/twrp$ 
> ```
> 
> 但是一直不行，請問你知道這個如何解決嗎? 如果是在vm 內則是正常，就可以繼續下一步，但是會導致VM 不夠(剩下2GB)
> 
> ```
> user@user-VirtualBox:~$ repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
> Downloading Repo source from https://gerrit.googlesource.com/git-repo
> repo: warning: Invalid UTF-8 output:
> cmd: ['git', 'tag', '-v', 'v2.32']
> b'gpg: Signature made \xe5\xbb\xbf\xe5\xbb\xbf\xe4\xb8\x89\xe5\xb9\xb4\xe4\xb8\x89\xe6\x9c\x88\xe4\xb8\x80\xe6\x97\xa5 (\xe9\x80\xb1\xe4\xb8\x89) \xe4\xba\x8c\xe6\x99\x82\xe5\xbb\xbf\xe4\xb8\x89\xe5\x88\ngpg:                using DSA key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65\ngpg: Good signature from "Repo Maintainer <repo@android.kernel.org>" [unknown]\ngpg: WARNING: This key is not certified with a trusted signature!\ngpg:          There is no indication that the signature belongs to the owner.\nPrimary key fingerprint: 8BB9 AD79 3E8E 6153 AF0F  9A44 1653 0D5E 920F 5C65\n'
> 
> Your identity is: besov007 <besov007@gmail.com>
> If you want to change this, please re-run 'repo init' with --config-name
> 
> repo has been initialized in /home/user
> ```



VirtualBox的硬碟空間，如果是動態分區可以直接調整使用
command:
.\VBoxManage.exe modifyhd "X:\123\456\OSTest.vdi" --resize 1024002

之後gparted 調整
apt-get install gparted

**Comment by ymdzq** [comment]
大概是文件系统问题吧，不要直接用虚拟机共享文件夹功能挂载ntfs分区，你直接在虚拟机的设置页面新增虚拟硬盘vdi或者vmdk，保存到你那第二个ssd上，在虚拟机里正常把第二个虚拟硬盘格式化成ext4分区

**Comment by skysumbra** [comment]
> 大概是文件系统问题吧，不要直接用虚拟机共享文件夹功能挂载ntfs分区，你直接在虚拟机的设置页面新增虚拟硬盘vdi或者vmdk，保存到你那第二个ssd上，在虚拟机里正常把第二个虚拟硬盘格式化成ext4分区

應該是，所以用直接改變vm 的容量方式

另外 #1F 
OFRP:
https://wiki.orangefox.tech/en/home
請問網址是這個的嗎? 沒有看到codebase 與說明如何使用

**Comment by skysumbra** [comment]
> > 大概是文件系统问题吧，不要直接用虚拟机共享文件夹功能挂载ntfs分区，你直接在虚拟机的设置页面新增虚拟硬盘vdi或者vmdk，保存到你那第二个ssd上，在虚拟机里正常把第二个虚拟硬盘格式化成ext4分区
> 
> 應該是，所以用直接改變vm 的容量方式
> 
> 另外 #1F OFRP: https://wiki.orangefox.tech/en/home 請問網址是這個的嗎? 沒有看到codebase 與說明如何使用

參考這個網頁，看不到得註冊一個帳號
https://gitlab.com/OrangeFox/sync

目前這個時間，這三個REC可以找到的版本號皆為12.1，也是最新版本
