### ISSUE TITLE
关于data解密的问题

### ISSUE THREAD

**Issue by YangQi0408** [ymdzq/OFRP-device_xiaomi_elish#9]
在临时启动OFRP后，查看sdcard分区时发现没有解密，然后又去看data分区也没有解密，我是没有设置锁屏密码的并且日志中也显示了解密成功，请问这是什么问题？

**Comment by ymdzq** [comment]
前几天删东西删过头了，把keymaster4.1删掉了，23.06.09应该没问题，我现在正在加回来重新编译23.07.04
